画笔颜色优化
WXRIW/Ink-Canvas pull request #101
Opened 2023-10-29 01:41 UTC by STBBRD

### 自定义画笔颜色
当配置文件 Colors/Dark.ini 或 Colors/Light.ini 存在时，指定工具栏中四个彩色画笔颜色为配置文件中的颜色
### 画笔颜色深色/浅色切换
- 当配置文件存在时，根据配置文件设置深色浅色各四个彩色画笔颜色；当配置文件不存在时，使用 Ink Canvas 画板默认的深色与浅色的彩色画笔颜色
- 在 3.x 浮动工具栏中进入屏幕批注模式或白板模式时，使用深色画笔；进入黑板模式时，使用浅色画笔
- 在 2.x 旧 UI 中使用新的深浅色切换方法
### 颜色配置文件
#### 介绍
- Colors/Dark.ini 和 Colors/Light.ini
- 一行一个颜色，一共四个，分别对应四个彩色画笔颜色
#### 范例
#FFFF00FF
#FF72EEFF
#FF008DFA
#FFFFF154
### 缺陷
我没做图形化自定义颜色工具

2023-11-01 04:09 UTC, clover-yan commented
读色彩没做错误处理，如果文件有问题会抛异常。~~（虽然一般人也不会去改就是了……）~~

2023-11-01 08:29 UTC, clover-yan commented
深色下的蓝色可以提亮一点。

2023-11-04 12:10 UTC, STBBRD commented
错误处理做好了
默认两套画笔颜色模式是照搬2.x的画笔颜色的，改了不知道WXRIW会不会同意

2023-11-25 13:07 UTC, STBBRD commented
某次上课发呆回过神来的时候发现 PPT 放映时出现了浅色画笔，但尝试多次无法复现。

2023-11-25 13:35 UTC, WXRIW requested changes
关机警告声有其他解决方法，先不要用这个。后期我去弄。

2023-12-02 12:16 UTC, STBBRD commented
> 关机警告声有其他解决方法，先不要用这个。后期我去弄。

好了

2023-12-16 04:12 UTC, clover-yan commented
> 某次上课发呆回过神来的时候发现 PPT 放映时出现了浅色画笔，但尝试多次无法复现。

@STBBRD 参看 #114 所述的白板内进入放映问题，当从白板内进入放映时会继续使用浅色画笔，建议在 `BtnSwitch_Click` 内做修改。

2023-12-23 12:48 UTC, STBBRD commented
> > 某次上课发呆回过神来的时候发现 PPT 放映时出现了浅色画笔，但尝试多次无法复现。
> 
> @STBBRD 参看 #114 所述的白板内进入放映问题，当从白板内进入放映时会继续使用浅色画笔，建议在 `BtnSwitch_Click` 而不是 `ImageBlackboard_MouseUp` 内做修改。

已修复

2024-03-14 08:15 UTC, WXRIW approved these changes

2024-03-14 08:19 UTC, merged